name: Deploy to Render

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to main branch
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: |
          # Add your test commands here if you have tests
          # python -m pytest tests/
          echo "No tests configured yet"

      - name: Deploy to Render
        run: |
          echo "Deployment triggered! Render will auto-deploy from this commit."
          echo "Check your Render dashboard at https://dashboard.render.com"

      # Note: Render automatically deploys when you push to the connected branch
      # No additional deployment step needed - just connect your repo to Render!

  # Optional: Notify on deployment
  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Deployment Status
        run: |
          echo "🚀 Deployment workflow completed!"
          echo "Your app will be live at: https://your-app-name.onrender.com"
          echo "Check Render dashboard for deployment status"
